[2024-11-02T14:49:50.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T14:49:50.202+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bas.bash_task manual__2024-11-02T13:16:04.045293+00:00 [queued]>
[2024-11-02T14:49:50.215+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bas.bash_task manual__2024-11-02T13:16:04.045293+00:00 [queued]>
[2024-11-02T14:49:50.216+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2024-11-02T14:49:50.246+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): bash_task> on 2024-11-02 13:16:04.045293+00:00
[2024-11-02T14:49:50.253+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1533) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T14:49:50.256+0000] {standard_task_runner.py:72} INFO - Started process 1534 to run task
[2024-11-02T14:49:50.255+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bas', 'bash_task', 'manual__2024-11-02T13:16:04.045293+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/templatin/tem.py', '--cfg-path', '/tmp/tmpl33xodfm']
[2024-11-02T14:49:50.257+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask bash_task
[2024-11-02T14:49:50.319+0000] {task_command.py:467} INFO - Running <TaskInstance: bas.bash_task manual__2024-11-02T13:16:04.045293+00:00 [running]> on host fe3e688f2b29
[2024-11-02T14:49:50.443+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adewunmi' AIRFLOW_CTX_DAG_ID='bas' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T13:16:04.045293+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T13:16:04.045293+00:00'
[2024-11-02T14:49:50.445+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T14:49:50.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T14:49:50.484+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash /opt/***/dags/templatin/wiki.sh ']
[2024-11-02T14:49:50.500+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T14:49:50.523+0000] {subprocess.py:93} INFO - {{ execution_date }}
[2024-11-02T14:49:50.524+0000] {subprocess.py:93} INFO - /opt/***/dags/templatin/wiki.sh: line 12: syntax error near unexpected token `('
[2024-11-02T14:49:50.525+0000] {subprocess.py:93} INFO - /opt/***/dags/templatin/wiki.sh: line 12: `curl -o /opt/***/dags/pageviews-{{ execution_date.year }}{{ '{:02}'.format(execution_date.month) }}{{ '{:02}'.format(execution_date.day) }}-{{ '{:02}'.format(execution_date.hour) }}0000.gz \'
[2024-11-02T14:49:50.526+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-02T14:49:50.545+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-02T14:49:50.559+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=bas, task_id=bash_task, run_id=manual__2024-11-02T13:16:04.045293+00:00, execution_date=20241102T131604, start_date=20241102T144950, end_date=20241102T144950
[2024-11-02T14:49:50.603+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T14:49:50.604+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task bash_task (Bash command failed. The command returned a non-zero exit code 2.; 1534)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-02T14:49:50.637+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-02T14:49:50.659+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T14:49:50.668+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
