[2024-11-02T13:16:06.015+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T13:16:06.043+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bas.bash_task manual__2024-11-02T13:16:04.045293+00:00 [queued]>
[2024-11-02T13:16:06.057+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bas.bash_task manual__2024-11-02T13:16:04.045293+00:00 [queued]>
[2024-11-02T13:16:06.059+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-02T13:16:06.086+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): bash_task> on 2024-11-02 13:16:04.045293+00:00
[2024-11-02T13:16:06.095+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T13:16:06.098+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bas', 'bash_task', 'manual__2024-11-02T13:16:04.045293+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/templatin/template.py', '--cfg-path', '/tmp/tmp3mug82ia']
[2024-11-02T13:16:06.099+0000] {standard_task_runner.py:72} INFO - Started process 227 to run task
[2024-11-02T13:16:06.100+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask bash_task
[2024-11-02T13:16:06.205+0000] {task_command.py:467} INFO - Running <TaskInstance: bas.bash_task manual__2024-11-02T13:16:04.045293+00:00 [running]> on host fe3e688f2b29
[2024-11-02T13:16:06.412+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adewunmi' AIRFLOW_CTX_DAG_ID='bas' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T13:16:04.045293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T13:16:04.045293+00:00'
[2024-11-02T13:16:06.413+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T13:16:06.444+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T13:16:06.445+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash /opt/***/dags/templatin/wiki.sh ']
[2024-11-02T13:16:06.460+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T13:16:06.491+0000] {subprocess.py:93} INFO - {{ execution_date }}
[2024-11-02T13:16:06.502+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-11-02T13:16:06.503+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-11-02T13:16:16.012+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0Warning: Failed to open the file
[2024-11-02T13:16:16.013+0000] {subprocess.py:93} INFO - Warning: /opt/***/dags/pageviews-20241102-110000.gz: No such file or
[2024-11-02T13:16:16.015+0000] {subprocess.py:93} INFO - Warning: directory
[2024-11-02T13:16:16.017+0000] {subprocess.py:93} INFO -   0 58.2M    0 16048    0     0   1687      0 10:03:51  0:00:09 10:03:42  3732
[2024-11-02T13:16:16.018+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-11-02T13:16:16.021+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-11-02T13:16:16.044+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-11-02T13:16:16.056+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=bas, task_id=bash_task, run_id=manual__2024-11-02T13:16:04.045293+00:00, execution_date=20241102T131604, start_date=20241102T131606, end_date=20241102T131616
[2024-11-02T13:16:16.084+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T13:16:16.087+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task bash_task (Bash command failed. The command returned a non-zero exit code 23.; 227)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-11-02T13:16:16.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-02T13:16:16.142+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T13:16:16.159+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
