[2024-11-25T02:00:41.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T02:00:41.497+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ckckc.read_from_datalake manual__2024-11-25T01:58:47.632514+00:00 [queued]>
[2024-11-25T02:00:41.517+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ckckc.read_from_datalake manual__2024-11-25T01:58:47.632514+00:00 [queued]>
[2024-11-25T02:00:41.518+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-11-25T02:00:41.554+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): read_from_datalake> on 2024-11-25 01:58:47.632514+00:00
[2024-11-25T02:00:41.567+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=398) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-25T02:00:41.570+0000] {standard_task_runner.py:72} INFO - Started process 400 to run task
[2024-11-25T02:00:41.570+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ckckc', 'read_from_datalake', 'manual__2024-11-25T01:58:47.632514+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/capstone_***/refractor_code_dag.py', '--cfg-path', '/tmp/tmpf0vg06hk']
[2024-11-25T02:00:41.575+0000] {standard_task_runner.py:105} INFO - Job 127: Subtask read_from_datalake
[2024-11-25T02:00:41.664+0000] {task_command.py:467} INFO - Running <TaskInstance: ckckc.read_from_datalake manual__2024-11-25T01:58:47.632514+00:00 [running]> on host 18d777ba90d1
[2024-11-25T02:00:41.831+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adewunmi' AIRFLOW_CTX_DAG_ID='ckckc' AIRFLOW_CTX_TASK_ID='read_from_datalake' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T01:58:47.632514+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T01:58:47.632514+00:00'
[2024-11-25T02:00:41.834+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T02:00:41.868+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/capstone_airflow/function/load_from_s3.py", line 18, in read_s3_parquet
    read_result = wr.s3.read_parquet(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 179, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_read_parquet.py", line 497, in read_parquet
    s3_client = _utils.client(service_name="s3", session=boto3_session)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 480, in client
    return ensure_session(session=session).client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/capstone_airflow/function/load_from_s3.py", line 31, in read_s3_parquet
    raise Exception(f"Error reading Parquet from S3: {str(e)}")
Exception: Error reading Parquet from S3: 'function' object has no attribute 'client'
[2024-11-25T02:00:41.919+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ckckc, task_id=read_from_datalake, run_id=manual__2024-11-25T01:58:47.632514+00:00, execution_date=20241125T015847, start_date=20241125T020041, end_date=20241125T020041
[2024-11-25T02:00:41.978+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T02:00:41.981+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 127 for task read_from_datalake (Error reading Parquet from S3: 'function' object has no attribute 'client'; 400)
Traceback (most recent call last):
  File "/opt/airflow/dags/capstone_airflow/function/load_from_s3.py", line 18, in read_s3_parquet
    read_result = wr.s3.read_parquet(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 179, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_read_parquet.py", line 497, in read_parquet
    s3_client = _utils.client(service_name="s3", session=boto3_session)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 480, in client
    return ensure_session(session=session).client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/capstone_airflow/function/load_from_s3.py", line 31, in read_s3_parquet
    raise Exception(f"Error reading Parquet from S3: {str(e)}")
Exception: Error reading Parquet from S3: 'function' object has no attribute 'client'
[2024-11-25T02:00:42.029+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-25T02:00:42.090+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T02:00:42.098+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
