[2024-10-07T18:15:32.743+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-07T18:15:32.766+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: compl_cssnowflake.load_to_snowflake manual__2024-10-07T18:15:13.514698+00:00 [queued]>
[2024-10-07T18:15:32.777+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: compl_cssnowflake.load_to_snowflake manual__2024-10-07T18:15:13.514698+00:00 [queued]>
[2024-10-07T18:15:32.778+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-07T18:15:32.802+0000] {taskinstance.py:2888} INFO - Executing <Task(SnowflakeOperator): load_to_snowflake> on 2024-10-07 18:15:13.514698+00:00
[2024-10-07T18:15:32.815+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3462) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T18:15:32.818+0000] {standard_task_runner.py:72} INFO - Started process 3464 to run task
[2024-10-07T18:15:32.817+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'compl_cssnowflake', 'load_to_snowflake', 'manual__2024-10-07T18:15:13.514698+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/school/ty.py', '--cfg-path', '/tmp/tmpc3gmu9ca']
[2024-10-07T18:15:32.819+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask load_to_snowflake
[2024-10-07T18:15:32.888+0000] {task_command.py:467} INFO - Running <TaskInstance: compl_cssnowflake.load_to_snowflake manual__2024-10-07T18:15:13.514698+00:00 [running]> on host 67bc14123253
[2024-10-07T18:15:33.037+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='seylow' AIRFLOW_CTX_DAG_ID='compl_cssnowflake' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T18:15:13.514698+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-07T18:15:13.514698+00:00'
[2024-10-07T18:15:33.039+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-07T18:15:33.040+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-07T18:15:33.042+0000] {logging_mixin.py:190} INFO - Current task name:load_to_snowflake state:running start_date:2024-10-07 18:15:32.767440+00:00
[2024-10-07T18:15:33.043+0000] {logging_mixin.py:190} INFO - Dag name:compl_cssnowflake and current dag run status:running
[2024-10-07T18:15:33.044+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-07T18:15:33.045+0000] {sql.py:266} INFO - Executing: 
        CREATE OR REPLACE TEMPORARY TABLE temp_arts_class AS
            SELECT * FROM school.data_schema.arts_class WHERE 1 = 0;  -- Create an empty table with the same structure as the target

        COPY INTO temp_arts_class
        FROM s3://my-first-terraform-bucket-jeda/arts_class 
        FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1);

        MERGE INTO school.data_schema.arts_class AS target
        USING temp_arts_class AS source
        ON target.student_id = source.student_id  -- Match based on the unique identifier, like student_id
        WHEN NOT MATCHED THEN
        INSERT (student_id, Maths_score, English_score, Civic_education_score, Economics_score, Government_score,
          CRS_score, Lit_in_Eng_score, Yoruba_score, History_score, Total_Grade_Points, Average_Score)
        VALUES (source.student_id, source.Maths_score, source.English_score, source.Civic_education_score,
          source.Economics_score, source.Government_score, source.CRS_score, source.Lit_in_Eng_score, source.Yoruba_score, source.History_score, source.Total_Grade_Points, source.Average_Score);

        DROP TABLE temp_arts_class;
        
[2024-10-07T18:15:33.065+0000] {base.py:84} INFO - Retrieving connection 'secondary'
[2024-10-07T18:15:33.082+0000] {base.py:84} INFO - Retrieving connection 'secondary'
[2024-10-07T18:15:33.084+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-10-07T18:15:33.085+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2024-10-07T18:15:33.086+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-10-07T18:15:34.588+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-07T18:15:34.589+0000] {sql.py:509} INFO - Running statement: CREATE OR REPLACE TEMPORARY TABLE temp_arts_class AS
            SELECT * FROM school.data_schema.arts_class WHERE 1 = 0;  -- Create an empty table with the same structure as the target, parameters: None
[2024-10-07T18:15:35.380+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-07T18:15:35.383+0000] {sql.py:518} INFO - Rows affected: 1
[2024-10-07T18:15:35.387+0000] {snowflake.py:422} INFO - Rows affected: 1
[2024-10-07T18:15:35.388+0000] {snowflake.py:423} INFO - Snowflake query id: 01b78927-0001-5f3f-0000-0001e512a3f9
[2024-10-07T18:15:35.388+0000] {sql.py:509} INFO - Running statement: COPY INTO temp_arts_class
        FROM s3://my-first-terraform-bucket-jeda/arts_class 
        FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1);, parameters: None
[2024-10-07T18:15:36.397+0000] {connection.py:788} INFO - closed
[2024-10-07T18:15:36.599+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2024-10-07T18:15:36.755+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 410, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 091003 (22000): 01b78927-0001-5f3f-0000-0001e512a3fd: Failure using stage area. Cause: [Access Denied (Status Code: 403; Error Code: AccessDenied)]
[2024-10-07T18:15:36.771+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-07T18:15:36.772+0000] {logging_mixin.py:190} INFO - Task start:2024-10-07 18:15:32.767440+00:00 end:2024-10-07 18:15:36.770596+00:00 duration:4.003156
[2024-10-07T18:15:36.773+0000] {logging_mixin.py:190} INFO - Task:<Task(SnowflakeOperator): load_to_snowflake> dag:<DAG: compl_cssnowflake> dagrun:<DagRun compl_cssnowflake @ 2024-10-07 18:15:13.514698+00:00: manual__2024-10-07T18:15:13.514698+00:00, state:running, queued_at: 2024-10-07 18:15:13.535242+00:00. externally triggered: True>
[2024-10-07T18:15:36.773+0000] {logging_mixin.py:190} INFO - Failure caused by 091003 (22000): 01b78927-0001-5f3f-0000-0001e512a3fd: Failure using stage area. Cause: [Access Denied (Status Code: 403; Error Code: AccessDenied)]
[2024-10-07T18:15:36.774+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=compl_cssnowflake, task_id=load_to_snowflake, run_id=manual__2024-10-07T18:15:13.514698+00:00, execution_date=20241007T181513, start_date=20241007T181532, end_date=20241007T181536
[2024-10-07T18:15:36.803+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-07T18:15:36.804+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task load_to_snowflake (091003 (22000): 01b78927-0001-5f3f-0000-0001e512a3fd: Failure using stage area. Cause: [Access Denied (Status Code: 403; Error Code: AccessDenied)]; 3464)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 410, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 091003 (22000): 01b78927-0001-5f3f-0000-0001e512a3fd: Failure using stage area. Cause: [Access Denied (Status Code: 403; Error Code: AccessDenied)]
[2024-10-07T18:15:36.860+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-07T18:15:36.891+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T18:15:36.903+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
