[2024-10-19T16:52:35.508+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T16:52:35.548+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-19T16:44:14.509632+00:00 [queued]>
[2024-10-19T16:52:35.574+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-19T16:44:14.509632+00:00 [queued]>
[2024-10-19T16:52:35.579+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T16:52:35.621+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-10-19 16:44:14.509632+00:00
[2024-10-19T16:52:35.632+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1499) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T16:52:35.635+0000] {standard_task_runner.py:72} INFO - Started process 1501 to run task
[2024-10-19T16:52:35.635+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_postgres', 'manual__2024-10-19T16:44:14.509632+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmpqf2c9vhk']
[2024-10-19T16:52:35.638+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask load_to_postgres
[2024-10-19T16:52:35.714+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-19T16:44:14.509632+00:00 [running]> on host 533638d20908
[2024-10-19T16:52:35.837+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T16:44:14.509632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T16:44:14.509632+00:00'
[2024-10-19T16:52:35.840+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T16:52:35.881+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-19T16:52:35.888+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-19T16:52:35.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T16:52:35.911+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_postgres, run_id=manual__2024-10-19T16:44:14.509632+00:00, execution_date=20241019T164414, start_date=20241019T165235, end_date=20241019T165235
[2024-10-19T16:52:35.974+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-19T16:52:36.025+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-19T16:52:36.030+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
