[2024-10-17T20:53:41.284+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T20:53:41.314+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T20:53:41.327+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T20:53:41.327+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-17T20:53:41.360+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-10-16 00:00:00+00:00
[2024-10-17T20:53:41.371+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1053) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T20:53:41.378+0000] {standard_task_runner.py:72} INFO - Started process 1055 to run task
[2024-10-17T20:53:41.377+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmp_84p7q29']
[2024-10-17T20:53:41.381+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask load_to_s3
[2024-10-17T20:53:41.465+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 scheduled__2024-10-16T00:00:00+00:00 [running]> on host 1b4cad12ae67
[2024-10-17T20:53:41.612+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T20:53:41.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T20:53:41.649+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-17T20:53:41.708+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/prod.py", line 37, in load_csv_to_database
    cursor.copy_expert("COPY wiki_file FROM STDIN WITH CSV HEADER DELIMITER ','", f)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY wiki_file, line 75: "bs.m,Datoteka:Domenikos_Theotokópoulos,_called_El_Greco_-_The_Assumption_of_the_Virgin_-_Google_Art..."

[2024-10-17T20:53:41.726+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T205341, end_date=20241017T205341
[2024-10-17T20:53:41.746+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T20:53:41.747+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task load_to_s3 (extra data after last expected column
CONTEXT:  COPY wiki_file, line 75: "bs.m,Datoteka:Domenikos_Theotokópoulos,_called_El_Greco_-_The_Assumption_of_the_Virgin_-_Google_Art..."
; 1055)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/prod.py", line 37, in load_csv_to_database
    cursor.copy_expert("COPY wiki_file FROM STDIN WITH CSV HEADER DELIMITER ','", f)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY wiki_file, line 75: "bs.m,Datoteka:Domenikos_Theotokópoulos,_called_El_Greco_-_The_Assumption_of_the_Virgin_-_Google_Art..."

[2024-10-17T20:53:41.797+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T20:53:41.824+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T20:53:41.830+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
