[2024-10-19T15:25:27.421+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T15:25:27.451+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-19T15:21:45.681062+00:00 [queued]>
[2024-10-19T15:25:27.466+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-19T15:21:45.681062+00:00 [queued]>
[2024-10-19T15:25:27.467+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-19T15:25:27.489+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-10-19 15:21:45.681062+00:00
[2024-10-19T15:25:27.504+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=240) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T15:25:27.507+0000] {standard_task_runner.py:72} INFO - Started process 242 to run task
[2024-10-19T15:25:27.506+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_postgres', 'manual__2024-10-19T15:21:45.681062+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmp4rjs609k']
[2024-10-19T15:25:27.511+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask load_to_postgres
[2024-10-19T15:25:27.599+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-19T15:21:45.681062+00:00 [running]> on host 533638d20908
[2024-10-19T15:25:28.011+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T15:21:45.681062+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T15:21:45.681062+00:00'
[2024-10-19T15:25:28.013+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T15:25:28.048+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-19T15:25:28.054+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-19T15:25:28.071+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T15:25:28.072+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_postgres, run_id=manual__2024-10-19T15:21:45.681062+00:00, execution_date=20241019T152145, start_date=20241019T152527, end_date=20241019T152528
[2024-10-19T15:25:28.128+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-19T15:25:28.174+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-19T15:25:28.178+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
