[2024-10-19T16:42:33.797+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T16:42:33.820+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-19T16:17:53.832695+00:00 [queued]>
[2024-10-19T16:42:33.834+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-19T16:17:53.832695+00:00 [queued]>
[2024-10-19T16:42:33.835+0000] {taskinstance.py:2865} INFO - Starting attempt 9 of 9
[2024-10-19T16:42:33.857+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-10-19 16:17:53.832695+00:00
[2024-10-19T16:42:33.867+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1349) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T16:42:33.869+0000] {standard_task_runner.py:72} INFO - Started process 1351 to run task
[2024-10-19T16:42:33.870+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'manual__2024-10-19T16:17:53.832695+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmpyd21o04f']
[2024-10-19T16:42:33.874+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask load_to_s3
[2024-10-19T16:42:33.938+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-19T16:17:53.832695+00:00 [running]> on host 533638d20908
[2024-10-19T16:42:34.067+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T16:17:53.832695+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T16:17:53.832695+00:00'
[2024-10-19T16:42:34.069+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T16:42:34.136+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-19T16:42:34.150+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-19T16:42:34.542+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-19T16:42:34.556+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T16:42:34.556+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=manual__2024-10-19T16:17:53.832695+00:00, execution_date=20241019T161753, start_date=20241019T164233, end_date=20241019T164234
[2024-10-19T16:42:34.618+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-19T16:42:34.647+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-19T16:42:34.655+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
