[2024-10-17T21:51:27.999+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T21:51:28.020+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-17T21:49:50.170774+00:00 [queued]>
[2024-10-17T21:51:28.032+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-17T21:49:50.170774+00:00 [queued]>
[2024-10-17T21:51:28.033+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 3
[2024-10-17T21:51:28.057+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-10-17 21:49:50.170774+00:00
[2024-10-17T21:51:28.071+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1829) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T21:51:28.074+0000] {standard_task_runner.py:72} INFO - Started process 1831 to run task
[2024-10-17T21:51:28.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'manual__2024-10-17T21:49:50.170774+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmpb512gpl2']
[2024-10-17T21:51:28.083+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask load_to_s3
[2024-10-17T21:51:28.185+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-17T21:49:50.170774+00:00 [running]> on host 1b4cad12ae67
[2024-10-17T21:51:28.316+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T21:49:50.170774+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T21:49:50.170774+00:00'
[2024-10-17T21:51:28.318+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T21:51:28.382+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-17T21:51:28.397+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-17T21:51:28.668+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-17T21:51:28.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T21:51:28.683+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=manual__2024-10-17T21:49:50.170774+00:00, execution_date=20241017T214950, start_date=20241017T215128, end_date=20241017T215128
[2024-10-17T21:51:28.734+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T21:51:28.755+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T21:51:28.768+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
